Add a no_bash_competion suppression file

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -39,14 +39,17 @@ export HISTTIMEFORMAT='%FT%T%z '
 shopt -s cmdhist
 
 # Load in bash_completion if we can find it.
-if [[ -r /usr/local/etc/bash_completion ]]
+if ! [[ -r ~/.config/stitch/ide/bash/no_bash_completion ]]
 then
-  source /usr/local/etc/bash_completion
-elif [[ -r /usr/share/bash-completion/bash_completion ]]
-then
-  source /usr/share/bash-completion/bash_completion
-else
-  echo "# Can't find bash-completion. You should install it." >&2
+  if [[ -r /usr/local/etc/bash_completion ]]
+  then
+    source /usr/local/etc/bash_completion
+  elif [[ -r /usr/share/bash-completion/bash_completion ]]
+  then
+    source /usr/share/bash-completion/bash_completion
+  else
+    echo "# Can't find bash-completion. You should install it." >&2
+  fi
 fi
 
 # set up the ssh agent if we can't connect to it
@@ -69,8 +72,11 @@ fi
 # set up git ps1
 if ! command -v __git_ps1 > /dev/null 2>&1
 then
-  echo "# Can't find __git_ps1. Not adding it to the prompt." >&2
-  __git_ps1() { return 0; }
+  if ! [[ -r ~/.config/stitch/ide/bash/no_bash_completion ]]
+  then
+      echo "# Can't find __git_ps1. Not adding it to the prompt." >&2
+  fi
+  __git_ps1() { :; }
 fi
 
 # only works if using __git_ps1 as a PROMPT_COMMAND
